services:
  db:
    container_name: block-n-scroll-db
    build:
      context: ./db
      dockerfile: docker/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-defaultrootpass}
      MYSQL_USER: ${MYSQL_USER:-bnsuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password1}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-blocknscroll}
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d/sql      
  web:
    container_name: block-n-scroll-web
    build:
      context: .
      dockerfile: ./web/docker/Dockerfile
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER:-bnsuser}:${MYSQL_PASSWORD:-password1}@db/${MYSQL_DATABASE:-blocknscroll}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html
      - vendor-data:/var/www/html/vendor
      - ./.env:/var/www/html/.env # mount .env separately
volumes:
  vendor-data: