DELETE FROM default_player_name;

INSERT INTO default_player_name (base_team_id, position, name) VALUES
(1, 'Blitzer', 'Aria'),
(1, 'Blitzer', 'Selene'),
(1, 'Blitzer', 'Kara'),
(1, 'Blitzer', 'Mira'),
(1, 'Blitzer', 'Talia'),
(1, 'Blocker', 'Rhea'),
(1, 'Blocker', 'Lyra'),
(1, 'Blocker', 'Veda'),
(1, 'Blocker', 'Nyla'),
(1, 'Blocker', 'Zara'),
(1, 'Catcher', 'Lina'),
(1, 'Catcher', 'Dara'),
(1, 'Catcher', 'Sera'),
(1, 'Catcher', 'Vina'),
(1, 'Catcher', 'Tara'),
(1, 'Lineman', 'Asha'),
(1, 'Lineman', 'Mina'),
(1, 'Lineman', 'Rina'),
(1, 'Lineman', 'Tina'),
(1, 'Lineman', 'Nina'),
(1, 'Lineman', 'Sara'),
(1, 'Lineman', 'Kira'),
(1, 'Lineman', 'Vira'),
(1, 'Lineman', 'Zina'),
(1, 'Lineman', 'Yara');
