INSERT INTO default_player_name (name, base_team_id, position) VALUES
('Grog Smashface', 13, 'Lineman'),
('Zog Bloodfist', 13, 'Lineman'),
('Brak Ironjaw', 13, 'Lineman'),
('Thok Stonecrusher', 13, 'Lineman'),
('Drok Skullsplitter', 13, 'Lineman'),
('Garnak Bonechewer', 13, 'Lineman'),
('Ruk Grimtusk', 13, 'Lineman'),
('Snagtooth', 13, 'Lineman'),
('Grub', 13, 'Lineman'),
('Brog', 13, 'Lineman'),
('Zug', 13, 'Lineman'),
('Lok', 13, 'Lineman'),
('Mag', 13, 'Lineman'),
('Rog', 13, 'Lineman'),
('Gash', 13, 'Lineman'),
('Thrag', 13, 'Lineman'),
('Krog', 13, 'Lineman'),
('Blarg', 13, 'Lineman'),
('Snurk', 13, 'Lineman'),
('Grak', 13, 'Lineman'),
('Ugg', 13, 'Blitzer'),
('Thok', 13, 'Blitzer'),
('Grog', 13, 'Blitzer'),
('Zug', 13, 'Blitzer'),
('Ruk', 13, 'Blitzer'),
('Blag', 13, 'Blitzer'),
('Grak', 13, 'Blitzer'),
('Snag', 13, 'Blitzer'),
('Krog', 13, 'Blitzer'),
('Brak', 13, 'Blitzer'),
('Zog', 13, 'Catcher'),
('Grub', 13, 'Catcher'),
('Brog', 13, 'Catcher'),
('Lok', 13, 'Catcher'),
('Mag', 13, 'Catcher'),
('Rog', 13, 'Catcher'),
('Gash', 13, 'Catcher'),
('Thrag', 13, 'Catcher'),
('Snurk', 13, 'Catcher'),
('Grak', 13, 'Catcher'),
('Grimtooth', 13, 'Thrower'),
('Blackfang', 13, 'Thrower'),
('Ironjaw', 13, 'Thrower'),
('Skullcrusher', 13, 'Thrower'),
('Bonechewer', 13, 'Thrower'),
('Bloodfist', 13, 'Thrower'),
('Grimblade', 13, 'Thrower'),
('Fang', 13, 'Thrower'),
('Throgg', 13, 'Thrower'),
('Grognak', 13, 'Thrower'),
('Brak', 13, 'Blocker'),
('Thok', 13, 'Blocker'),
('Grog', 13, 'Blocker'),
('Zug', 13, 'Blocker'),
('Ruk', 13, 'Blocker'),
('Blag', 13, 'Blocker'),
('Grak', 13, 'Blocker'),
('Snag', 13, 'Blocker'),
('Krog', 13, 'Blocker'),
('Brak', 13, 'Blocker');
