INSERT INTO default_player_name (name, base_team_id, position) VALUES
('Grog Smashface', 14, 'Lineman'),
('Zog Bloodfist', 14, 'Lineman'),
('Brak Ironjaw', 14, 'Lineman'),
('Thok Stonecrusher', 14, 'Lineman'),
('Drok Skullsplitter', 14, 'Lineman'),
('Garnak Bonechewer', 14, 'Lineman'),
('Ruk Grimtusk', 14, 'Lineman'),
('Snagtooth', 14, 'Lineman'),
('Grub', 14, 'Lineman'),
('Brog', 14, 'Lineman'),
('Zug', 14, 'Lineman'),
('Lok', 14, 'Lineman'),
('Mag', 14, 'Lineman'),
('Rog', 14, 'Lineman'),
('Gash', 14, 'Lineman'),
('Thrag', 14, 'Lineman'),
('Krog', 14, 'Lineman'),
('Blarg', 14, 'Lineman'),
('Snurk', 14, 'Lineman'),
('Grak', 14, 'Lineman'),
('Ugg', 14, 'Blitzer'),
('Thok', 14, 'Blitzer'),
('Grog', 14, 'Blitzer'),
('Zug', 14, 'Blitzer'),
('Ruk', 14, 'Blitzer'),
('Blag', 14, 'Blitzer'),
('Grak', 14, 'Blitzer'),
('Snag', 14, 'Blitzer'),
('Krog', 14, 'Blitzer'),
('Brak', 14, 'Blitzer'),
('Zog', 14, 'Catcher'),
('Grub', 14, 'Catcher'),
('Brog', 14, 'Catcher'),
('Lok', 14, 'Catcher'),
('Mag', 14, 'Catcher'),
('Rog', 14, 'Catcher'),
('Gash', 14, 'Catcher'),
('Thrag', 14, 'Catcher'),
('Snurk', 14, 'Catcher'),
('Grak', 14, 'Catcher'),
('Grimtooth', 14, 'Thrower'),
('Blackfang', 14, 'Thrower'),
('Ironjaw', 14, 'Thrower'),
('Skullcrusher', 14, 'Thrower'),
('Bonechewer', 14, 'Thrower'),
('Bloodfist', 14, 'Thrower'),
('Grimblade', 14, 'Thrower'),
('Fang', 14, 'Thrower'),
('Throgg', 14, 'Thrower'),
('Grognak', 14, 'Thrower'),
('Brak', 14, 'Blocker'),
('Thok', 14, 'Blocker'),
('Grog', 14, 'Blocker'),
('Zug', 14, 'Blocker'),
('Ruk', 14, 'Blocker'),
('Blag', 14, 'Blocker'),
('Grak', 14, 'Blocker'),
('Snag', 14, 'Blocker'),
('Krog', 14, 'Blocker'),
('Brak', 14, 'Blocker');
