INSERT INTO default_player_name (base_team_id, position, name) VALUES
(31, 'Big Guy', 'Grog'),
(31, 'Big Guy', 'Throg'),
(31, 'Big Guy', 'Brak'),
(31, 'Big Guy', 'Krug'),
(31, 'Big Guy', 'Snag'),
(31, 'Big Guy', 'Blarg'),
(31, 'Big Guy', 'Rug'),
(31, 'Big Guy', 'Skag'),
(31, 'Big Guy', 'Gruk'),
(31, 'Big Guy', 'Zog'),
(31, 'Lineman', 'Snotzug'),
(31, 'Lineman', 'Snotgob'),
(31, 'Lineman', 'Snotrag'),
(31, 'Lineman', 'Snotzog'),
(31, 'Lineman', 'Snotkrug'),
(31, 'Lineman', 'Snotblarg'),
(31, 'Lineman', 'Snotrug'),
(31, 'Lineman', 'Snotskag'),
(31, 'Lineman', 'Snotgruk'),
(31, 'Lineman', 'Snotzog');
