INSERT INTO default_player_names (race_id, position, name) VALUES
(34, 'Big Guy', 'Grog'),
(34, 'Big Guy', 'Throg'),
(34, 'Big Guy', 'Brak'),
(34, 'Big Guy', 'Krug'),
(34, 'Big Guy', 'Snag'),
(34, 'Big Guy', 'Blarg'),
(34, 'Big Guy', 'Rug'),
(34, 'Big Guy', 'Skag'),
(34, 'Big Guy', 'Gruk'),
(34, 'Big Guy', 'Zog'),
(34, 'Lineman', 'Snotzug'),
(34, 'Lineman', 'Snotgob'),
(34, 'Lineman', 'Snotrag'),
(34, 'Lineman', 'Snotzog'),
(34, 'Lineman', 'Snotkrug'),
(34, 'Lineman', 'Snotblarg'),
(34, 'Lineman', 'Snotrug'),
(34, 'Lineman', 'Snotskag'),
(34, 'Lineman', 'Snotgruk'),
(34, 'Lineman', 'Snotzog');
