INSERT INTO default_player_names (name, race, position) VALUES
('Grog Smashface', 'Orcs', 'Lineman'),
('Zog Bloodfist', 'Orcs', 'Lineman'),
('Brak Ironjaw', 'Orcs', 'Lineman'),
('Thok Stonecrusher', 'Orcs', 'Lineman'),
('Drok Skullsplitter', 'Orcs', 'Lineman'),
('Garnak Bonechewer', 'Orcs', 'Lineman'),
('Ruk Grimtusk', 'Orcs', 'Lineman'),
('Snagtooth', 'Orcs', 'Lineman'),
('Grub', 'Orcs', 'Lineman'),
('Brog', 'Orcs', 'Lineman'),
('Zug', 'Orcs', 'Lineman'),
('Lok', 'Orcs', 'Lineman'),
('Mag', 'Orcs', 'Lineman'),
('Rog', 'Orcs', 'Lineman'),
('Gash', 'Orcs', 'Lineman'),
('Thrag', 'Orcs', 'Lineman'),
('Krog', 'Orcs', 'Lineman'),
('Blarg', 'Orcs', 'Lineman'),
('Snurk', 'Orcs', 'Lineman'),
('Grak', 'Orcs', 'Lineman'),
('Ugg', 'Orcs', 'Blitzer'),
('Thok', 'Orcs', 'Blitzer'),
('Grog', 'Orcs', 'Blitzer'),
('Zug', 'Orcs', 'Blitzer'),
('Ruk', 'Orcs', 'Blitzer'),
('Blag', 'Orcs', 'Blitzer'),
('Grak', 'Orcs', 'Blitzer'),
('Snag', 'Orcs', 'Blitzer'),
('Krog', 'Orcs', 'Blitzer'),
('Brak', 'Orcs', 'Blitzer'),
('Zog', 'Orcs', 'Catcher'),
('Grub', 'Orcs', 'Catcher'),
('Brog', 'Orcs', 'Catcher'),
('Lok', 'Orcs', 'Catcher'),
('Mag', 'Orcs', 'Catcher'),
('Rog', 'Orcs', 'Catcher'),
('Gash', 'Orcs', 'Catcher'),
('Thrag', 'Orcs', 'Catcher'),
('Snurk', 'Orcs', 'Catcher'),
('Grak', 'Orcs', 'Catcher'),
('Grimtooth', 'Orcs', 'Thrower'),
('Blackfang', 'Orcs', 'Thrower'),
('Ironjaw', 'Orcs', 'Thrower'),
('Skullcrusher', 'Orcs', 'Thrower'),
('Bonechewer', 'Orcs', 'Thrower'),
('Bloodfist', 'Orcs', 'Thrower'),
('Grimblade', 'Orcs', 'Thrower'),
('Fang', 'Orcs', 'Thrower'),
('Throgg', 'Orcs', 'Thrower'),
('Grognak', 'Orcs', 'Thrower'),
('Brak', 'Orcs', 'Blocker'),
('Thok', 'Orcs', 'Blocker'),
('Grog', 'Orcs', 'Blocker'),
('Zug', 'Orcs', 'Blocker'),
('Ruk', 'Orcs', 'Blocker'),
('Blag', 'Orcs', 'Blocker'),
('Grak', 'Orcs', 'Blocker'),
('Snag', 'Orcs', 'Blocker'),
('Krog', 'Orcs', 'Blocker'),
('Brak', 'Orcs', 'Blocker');
