INSERT INTO default_player_names (race_id, position, name) VALUES
(33, 'Lineman', 'Tutancomon'),
(33, 'Lineman', 'Anubis'),
(33, 'Lineman', 'Ra'),
(33, 'Lineman', 'Osiris'),
(33, 'Lineman', 'Horus'),
(33, 'Lineman', 'Seti'),
(33, 'Lineman', 'Amun'),
(33, 'Lineman', 'Bastet'),
(33, 'Lineman', 'Sekhmet'),
(33, 'Blitzer', 'Tutankhamun'),
(33, 'Blitzer', 'Cleopatra'),
(33, 'Blitzer', 'Nefertiti'),
(33, 'Blitzer', 'Ramses'),
(33, 'Thrower', 'Imhotep'),
(33, 'Thrower', 'Akhenaten'),
(33, 'Thrower', 'Hatshepsut'),
(33, 'Thrower', 'Thutmose'),
(33, 'Catcher', 'Isis'),
(33, 'Catcher', 'Nephthys'),
(33, 'Big Guy', 'Anubis the Jackal'),
(33, 'Big Guy', 'Sobek the Crocodile'),
(33, 'Big Guy', 'Horus the Falcon'),
(33, 'Big Guy', 'Set the Chaos God'),
(33, 'Big Guy', 'Ra the Sun God');