INSERT INTO default_player_names (name, race_id, position) VALUES
('Grog Smashface', 15, 'Lineman'),
('Zog Bloodfist', 15, 'Lineman'),
('Brak Ironjaw', 15, 'Lineman'),
('Thok Stonecrusher', 15, 'Lineman'),
('Drok Skullsplitter', 15, 'Lineman'),
('Garnak Bonechewer', 15, 'Lineman'),
('Ruk Grimtusk', 15, 'Lineman'),
('Snagtooth', 15, 'Lineman'),
('Grub', 15, 'Lineman'),
('Brog', 15, 'Lineman'),
('Zug', 15, 'Lineman'),
('Lok', 15, 'Lineman'),
('Mag', 15, 'Lineman'),
('Rog', 15, 'Lineman'),
('Gash', 15, 'Lineman'),
('Thrag', 15, 'Lineman'),
('Krog', 15, 'Lineman'),
('Blarg', 15, 'Lineman'),
('Snurk', 15, 'Lineman'),
('Grak', 15, 'Lineman'),
('Ugg', 15, 'Blitzer'),
('Thok', 15, 'Blitzer'),
('Grog', 15, 'Blitzer'),
('Zug', 15, 'Blitzer'),
('Ruk', 15, 'Blitzer'),
('Blag', 15, 'Blitzer'),
('Grak', 15, 'Blitzer'),
('Snag', 15, 'Blitzer'),
('Krog', 15, 'Blitzer'),
('Brak', 15, 'Blitzer'),
('Zog', 15, 'Catcher'),
('Grub', 15, 'Catcher'),
('Brog', 15, 'Catcher'),
('Lok', 15, 'Catcher'),
('Mag', 15, 'Catcher'),
('Rog', 15, 'Catcher'),
('Gash', 15, 'Catcher'),
('Thrag', 15, 'Catcher'),
('Snurk', 15, 'Catcher'),
('Grak', 15, 'Catcher'),
('Grimtooth', 15, 'Thrower'),
('Blackfang', 15, 'Thrower'),
('Ironjaw', 15, 'Thrower'),
('Skullcrusher', 15, 'Thrower'),
('Bonechewer', 15, 'Thrower'),
('Bloodfist', 15, 'Thrower'),
('Grimblade', 15, 'Thrower'),
('Fang', 15, 'Thrower'),
('Throgg', 15, 'Thrower'),
('Grognak', 15, 'Thrower'),
('Brak', 15, 'Blocker'),
('Thok', 15, 'Blocker'),
('Grog', 15, 'Blocker'),
('Zug', 15, 'Blocker'),
('Ruk', 15, 'Blocker'),
('Blag', 15, 'Blocker'),
('Grak', 15, 'Blocker'),
('Snag', 15, 'Blocker'),
('Krog', 15, 'Blocker'),
('Brak', 15, 'Blocker');
