INSERT INTO default_player_names (race_id, position, name) VALUES
(13, 'Lineman', 'Vlad'),
(13, 'Lineman', 'Dracula'),
(13, 'Lineman', 'Nosferatu'),
(13, 'Lineman', 'Alucard'),
(13, 'Lineman', 'Count'),
(13, 'Lineman', 'Carmilla'),
(13, 'Lineman', 'Lucian'),
(13, 'Lineman', 'Mina'),
(13, 'Lineman', 'Renfield'),
(13, 'Lineman', 'Van Helsing'),
(13, 'Blitzer', 'Vlad the Impaler'),
(13, 'Blitzer', 'Count Orlok'),
(13, 'Blitzer', 'Dracula Untold'),
(13, 'Blitzer', 'Nosferatu the Vampire'),
(13, 'Blitzer', 'Alucard the Immortal'),
(13, 'Thrower', 'Lucian the Cursed'),
(13, 'Thrower', 'Mina Harker'),
(13, 'Thrower', 'Renfield the Madman'),
(13, 'Thrower', 'Van Helsing the Hunter'),
(13, 'Catcher', 'Carmilla the Seductress'),
(13, 'Catcher', 'Countess Bathory');