INSERT INTO skill (id, name, type, description) VALUES
-- GENERAL
(1, 'Block', 'General', 'This player does not get Knocked Down when blocking.'),
(2, 'Dauntless', 'General', 'When blocking a stronger opponent, roll D6 + own Strength; if equal or higher, use own Strength for Block.'),
(3, 'Dirty Player', 'General', 'Adds +1 to Armour or Injury rolls when Fouling.'),
(4, 'Fend', 'General', 'Opponents cannot follow up after pushing this player back.'),
(5, 'Frenzy', 'General', 'Must follow up and attempt a second Block if the initial Block pushes the opponent back.'),
(6, 'Kick', 'General', 'Improves control over kick placement during Kick-Off.'),
(7, 'Kick-Off Return', 'General', 'Allows additional movement during Kick-Off Return.'),
(8, 'Pass Block', 'General', 'This player blocks the passer instead of the ball carrier.'),
(9, 'Pro', 'General', 'Once per turn, may reroll any single dice roll of 3 or higher.'),
(10, 'Shadowing', 'General', 'Follows adjacent moving opponents if winning opposed 2D6 + Movement roll.'),
(11, 'Strip Ball', 'General', 'When this player blocks an opponent carrying the ball, the ball scatters instead of being automatically caught.'),
(12, 'Sure Hands', 'General', 'Rerolls failed Pick-up rolls and immune to Strip Ball effects.'),
(13, 'Tackle', 'General', 'Prevents opponent from using Dodge skill when blocked or dodging into tackle zone.'),
(14, 'Wrestle', 'General', 'Can block with tackle zones and prevents Both Down results on pushes.'),

-- AGILITY
(15, 'Catch', 'Agility', 'Allows rerolling failed Catch rolls from accurate passes.'),
(16, 'Defensive', 'Agility', 'Improves ability to intercept or catch in defense.'),
(17, 'Diving Catch', 'Agility', 'Can catch the ball from adjacent squares and gains +1 to Catch rolls for accurate passes.'),
(18, 'Diving Tackle', 'Agility', 'May go prone to apply -2 to adjacent opponent''s Dodge roll when they attempt to dodge away.'),
(19, 'Dodge', 'Agility', 'Allows rerolling failed Dodge rolls.'),
(20, 'Jump Up', 'Agility', 'Can stand up for free and block immediately without using movement.'),
(21, 'Leap', 'Agility', 'Leaps into adjacent squares ignoring tackle zones, applying -1 per opposing tackle zone entered.'),
(22, 'Safe Pair of Hands', 'Agility', 'Keeps ball in current square when falling, preventing scatter.'),
(23, 'Sidestep', 'Agility', 'Chooses destination square when pushed.'),
(24, 'Sneaky Git', 'Agility', 'Not sent off for doubles on Fouls unless injury occurs.'),
(25, 'Sprint', 'Agility', 'Can Rush three times per turn.'),
(26, 'Sure Feet', 'Agility', 'Rerolls failed Rush rolls.'),

-- PASSING
(27, 'Accurate', 'Passing', '+1 to Passing Ability tests when passing.'),
(28, 'Cannoneer', 'Passing', '+1 to Passing Ability tests for Long and Long Bomb passes.'),
(29, 'Cloud Burster', 'Passing', '-1 to opponent Intercept rolls for Long Bomb passes.'),
(30, 'Dump-Off', 'Passing', 'Allows a quick pass to a nearby teammate after a Block action.'),
(31, 'Fumblerooskie', 'Passing', 'If Pass action fails, ball stays in the passer''s square instead of turning over.'),
(32, 'Give and Go', 'Passing', 'After passing, allows moving again for a short distance.'),
(33, 'Hail Mary Pass', 'Passing', 'Declares a pass that automatically misses, but may target any square on the pitch.'),
(34, 'Leader', 'Passing', 'Grants one additional team reroll per half.'),
(35, 'Nerves of Steel', 'Passing', 'Ignores opponent tackle zones when Passing, Catching, or Intercepting.'),
(36, 'On The Ball', 'Passing', 'May move 3 squares when opponent declares a Pass or during Kick-Off.'),
(37, 'Pass', 'Passing', 'Once per turn rerolls a failed Passing Ability test.'),
(38, 'Portal Passer', 'Passing', 'Allows teleportation of the ball to another player.'),
(39, 'Running Pass', 'Passing', 'May continue moving after a successful Quick Pass.'),
(40, 'Safe Pass', 'Passing', 'Fumbled Pass does not cause turnover; ball remains in possession.'),
(41, 'Wall Thrower', 'Passing', 'May throw the ball over or around a wall of opponents.'),

-- STRENGTH
(42, 'Arm Bar', 'Strength', '+1 to Armour rolls when opponent fails Dodge or Jump from adjacent square.'),
(43, 'Brawler', 'Strength', 'May reroll one Both Down result when blocking during own activation.'),
(44, 'Break Tackle', 'Strength', 'Once per activation, may use Strength instead of Agility for Dodge.'),
(45, 'Grab', 'Strength', 'May push opponents into any adjacent square, negating Side Step.'),
(46, 'Guard', 'Strength', 'Can assist Blocks regardless of being in opponent''s tackle zone.'),
(47, 'Juggernaut', 'Strength', 'During Blitz, treats Both Down results as Push; negates Stand Firm and Wrestle.'),
(48, 'Mighty Blow', 'Strength', '+1 to Armour or Injury roll after Block.'),
(49, 'Multiple Block', 'Strength', 'Blocks two adjacent opponents simultaneously with separate dice pools.'),
(50, 'Piling On', 'Strength', 'May follow up a Knock Down and immediately commit a Foul.'),
(51, 'Pile Driver', 'Strength', 'May follow up a Knock Down and immediately perform a second Block.'),
(52, 'Stand Firm', 'Strength', 'Cannot be pushed unless Knocked Down.'),
(53, 'Strong Arm', 'Strength', '+1 to Throw Team-mate Passing Ability tests.'),
(54, 'Thick Skull', 'Strength', 'On KO, roll D6: 4+ results in Stun instead of KO.'),

-- MUTATION
(55, 'Big Hand', 'Mutation', 'Ignores tackle zones when picking up the ball.'),
(56, 'Claws', 'Mutation', 'Armour breaks on 8+ regardless of target''s Armour Value.'),
(57, 'Disturbing Presence', 'Mutation', '-1 to opponents'' Passing, Catch, or Intercept tests within 3 squares.'),
(58, 'Extra Arms', 'Mutation', '+1 to Pick-up, Intercept, and Catch rolls.'),
(59, 'Foul Appearance', 'Mutation', 'Opponent rolls D6 before Block; on 1, the Block automatically fails.'),
(60, 'Horns', 'Mutation', '+1 Strength when Blitzing.'),
(61, 'Iron Hard Skin', 'Mutation', 'Unaffected by Claws skill.'),
(62, 'Monstrous Mouth', 'Mutation', 'Rerolls failed Catch rolls and immune to Strip Ball effects.'),
(63, 'Prehensile Tail', 'Mutation', '-1 to Dodge rolls for opponents dodging away from this player.'),
(64, 'Tentacles', 'Mutation', 'Opposed 2D6 + Strength check to prevent adjacent opponent moving away.'),
(65, 'Two Heads', 'Mutation', '+1 to Dodge rolls.'),
(66, 'Very Long Legs', 'Mutation', '+2 to Intercept tests and ignores Cloud Burster.'),

-- EXTRAORDINARY
(67, 'Always Hungry', 'Extraordinary', 'Roll D6 when attempting Throw Team-mate; on 1, team-mate may be eaten.'),
(68, 'Animal Savagery', 'Extraordinary', 'On activation, roll D6; on 1-3, must Block adjacent team-mate or lose activation.'),
(69, 'Animosity', 'Extraordinary', 'Must Block adjacent teammates or opponent, losing activation if unable.'),
(70, 'Ball & Chain', 'Extraordinary', 'Causes a -1 to Dodge rolls against this player.'),
(71, 'Bloodlust', 'Extraordinary', 'Must attempt to Block each turn, losing activation if unable.'),
(72, 'Bombardier', 'Extraordinary', 'May throw bombs during Blitz actions.'),
(73, 'Bone Head', 'Extraordinary', 'Roll D6 on activation; on 1, lose Tackle Zones and end activation.'),
(74, 'Breathe Fire', 'Extraordinary', 'May perform a fiery breath attack instead of a Block.'),
(75, 'Chainsaw', 'Extraordinary', 'Adds +3 to Armour rolls when Blocking or Fouling; knocked down if turnover occurs.'),
(76, 'Decay', 'Extraordinary', 'Causes injury on opponent knockdowns.'),
(77, 'Drunkard', 'Extraordinary', 'May reroll failed Block dice but suffers penalties elsewhere.'),
(78, 'Fan Favorite', 'Extraordinary', 'Can use re-rolls on any dice rolls during the game.'),
(79, 'Hit and Run', 'Extraordinary', 'May make multiple Blitzes or Blocks per turn.'),
(80, 'Hypnotic Gaze', 'Extraordinary', 'Replaces Block with Agility test to remove opponent tackle zones.'),
(81, 'Kick Team-mate', 'Extraordinary', 'May kick a team-mate to move them instead of the ball.'),
(82, 'Loner', 'Extraordinary', 'Must roll 4+ to use team rerolls.'),
(83, 'My Ball', 'Extraordinary', 'Automatically catches the ball from any teammate within 3 squares.'),
(84, 'No Hands', 'Extraordinary', 'Cannot pick up or catch the ball.'),
(85, 'Pick-Me-Up', 'Extraordinary', 'Can pick up and throw teammates.'),
(86, 'Plague Ridden', 'Extraordinary', 'Causes injuries to adjacent opponents at end of their turns.'),
(87, 'Pogo Stick', 'Extraordinary', 'May leap over opponents without penalties.'),
(88, 'Projectile Vomit', 'Extraordinary', 'May perform a ranged vomit attack causing injury.'),
(89, 'Really Stupid', 'Extraordinary', 'May lose activation randomly.'),
(90, 'Regeneration', 'Extraordinary', 'Rerolls KO and injury results.'),
(91, 'Right Stuff', 'Extraordinary', 'Ignores injury on turnover results.'),
(92, 'Secret Weapon', 'Extraordinary', 'Appears randomly in the team; unknown until activated.'),
(93, 'Stab', 'Extraordinary', 'Ignores armour on injury rolls.'),
(94, 'Stakes', 'Extraordinary', 'Causes extra damage when causing injuries.'),
(95, 'Stunty', 'Extraordinary', 'Small size; harder to hit but also harder to block.'),
(96, 'Swarming', 'Extraordinary', 'Multiple players may gang up to Block a single opponent.'),
(97, 'Swoop', 'Extraordinary', 'May swoop into any square without movement penalties.'),
(98, 'Take Root', 'Extraordinary', 'Cannot be pushed when standing still.'),
(99, 'Throw Team-Mate', 'Extraordinary', 'May throw teammates to other squares.'),
(100, 'Timmm-ber!', 'Extraordinary', 'May chop down opponents blocking movement.'),
(101, 'Titchy', 'Extraordinary', 'Small stature; harder to hit with Blocks.'),
(102, 'Trickster', 'Extraordinary', 'Can reroll opponent''s successful dice rolls once per turn.'),
(103, 'Unchannelled Fury', 'Extraordinary', 'Must always Block an opponent when able.');

