INSERT INTO skill (id, name, category, description) VALUES
-- GENERAL
(1, 'Block', 'General', 'A player with the Block skill is proficient at knocking opponents down. The Block skill, if used, affects the results rolled with the Block dice, as explained in the Blocking rules.'),
(2, 'Dauntless', 'General', "When blocking a stronger opponent, roll a D6 and add it to the player's Strength. If the total exceeds the opponent's Strength, the player temporarily matches the opponent's Strength for that block. If not, the player uses their normal Strength. This roll happens before assists but after other modifiers."),
(3, 'Dirty Player', 'General', 'Adds +1 to Armour or Injury rolls when Fouling.'),
(4, 'Fend', 'General', 'Opponents cannot follow up after pushing this player back.'),
(5, 'Frenzy', 'General', 'Must follow up and attempt a second Block if the initial Block pushes the opponent back.'),
(6, 'Kick', 'General', 'Improves control over kick placement during Kick-Off.'),
(7, 'Kick-Off Return', 'General', 'Allows additional movement during Kick-Off Return.'),
(8, 'Pass Block', 'General', 'This player blocks the passer instead of the ball carrier.'),
(9, 'Pro', 'General', 'Once per turn, may reroll any single dice roll of 3 or higher.'),
(10, 'Shadowing', 'General', 'Follows adjacent moving opponents if winning opposed 2D6 + Movement roll.'),
(11, 'Strip Ball', 'General', 'When this player blocks an opponent carrying the ball, the ball scatters instead of being automatically caught.'),
(12, 'Sure Hands', 'General', 'Rerolls failed Pick-up rolls and immune to Strip Ball effects.'),
(13, 'Tackle', 'General', 'Prevents opponent from using Dodge skill when blocked or dodging into tackle zone.'),
(14, 'Wrestle', 'General', 'Can block with tackle zones and prevents Both Down results on pushes.'),

-- AGILITY
(15, 'Catch', 'Agility', 'A player who has the Catch skill is allowed to re-roll the D6 if he fails a catch roll. It also allows the player to re-roll the D6 if he drops a hand-off or fails to make an interception.'),
(16, 'Defensive', 'Agility', 'During your opponent’s team turn (but not during your own team), any opposition player being marked by this player cannot use the guard skill.'),
(17, 'Diving Catch', 'Agility', 'Can catch the ball from adjacent squares and gains +1 to Catch rolls for accurate passes.'),
(18, 'Diving Tackle', 'Agility', 'May go prone to apply -2 to adjacent opponent''s Dodge roll when they attempt to dodge away.'),
(19, 'Dodge', 'Agility', 'Allows rerolling failed Dodge rolls.'),
(20, 'Jump Up', 'Agility', 'Can stand up for free and block immediately without using movement.'),
(21, 'Leap', 'Agility', 'Leaps into adjacent squares ignoring tackle zones, applying -1 per opposing tackle zone entered.'),
(22, 'Safe Pair of Hands', 'Agility', 'If player Knocked Down, ball does not bounce.'),
(23, 'Sidestep', 'Agility', 'Chooses destination square when pushed.'),
(24, 'Sneaky Git', 'Agility', 'Not sent off for rolling doubles against Armour Roll.'),
(25, 'Sprint', 'Agility', 'Can Rush three times per turn.'),
(26, 'Sure Feet', 'Agility', 'Once per team turn, reroll a failed Rush.'),

-- PASSING
(27, 'Accurate', 'Passing', '+1 to Passing Ability tests when passing.'),
(28, 'Cannoneer', 'Passing', '+1 to Passing Ability tests for Long and Long Bomb passes.'),
(29, 'Cloud Burster', 'Passing', 'During Long Pass action or Long Bomb Pass action, make the opposing coach re-roll a successful attempt to interfere with the pass.'),
(30, 'Dump-Off', 'Passing', 'Allows a quick pass to a nearby teammate after a Block action.'),
(31, 'Fumblerooskie', 'Passing', 'Place/drop ball in vacated square without causing a turnover.'),
(32, 'Give and Go', 'Passing', 'After passing, allows moving again for a short distance.'),
(33, 'Hail Mary Pass', 'Passing', 'Declares a pass that automatically misses, but may target any square on the pitch.'),
(34, 'Leader', 'Passing', 'Grants one additional team reroll per half.'),
(35, 'Nerves of Steel', 'Passing', 'Ignores opponent tackle zones when Passing, Catching, or Intercepting.'),
(36, 'On The Ball', 'Passing', 'May move 3 squares when opponent declares a Pass or during Kick-Off.'),
(37, 'Pass', 'Passing', 'Once per turn rerolls a failed Passing Ability test.'),
(38, 'Portal Passer', 'Passing', 'During its activation, when this player teleports using a Portal, it may declare a Pass action after determining which Portal it is teleporting to.'),
(39, 'Running Pass', 'Passing', 'May continue moving after a successful Quick Pass.'),
(40, 'Safe Pass', 'Passing', 'Fumbled Pass does not cause turnover; ball remains in possession.'),
(41, 'Wall Thrower', 'Passing', 'When this player throws the ball at the wall, they may apply an additional +1 modifier when testing for the accuracy of the pass.'),

-- STRENGTH
(42, 'Arm Bar', 'Strength', '+1 to Armour rolls when opponent fails Dodge or Jump from adjacent square.'),
(43, 'Brawler', 'Strength', 'May reroll one Both Down result when blocking during own activation.'),
(44, 'Break Tackle', 'Strength', 'Once per activation, may use Strength instead of Agility for Dodge.'),
(45, 'Grab', 'Strength', 'May push opponents into any adjacent square, negating Side Step.'),
(46, 'Guard', 'Strength', 'Can assist Blocks regardless of being in opponent''s tackle zone.'),
(47, 'Juggernaut', 'Strength', 'During Blitz, treats Both Down results as Push; negates Stand Firm and Wrestle.'),
(48, 'Mighty Blow', 'Strength', '+1 to Armour or Injury roll after Block.'),
(49, 'Multiple Block', 'Strength', 'Blocks two adjacent opponents simultaneously with separate dice pools.'),
(50, 'Piling On', 'Strength', 'May follow up a Knock Down and immediately commit a Foul.'),
(51, 'Pile Driver', 'Strength', 'May follow up a Knock Down and immediately perform a second Block.'),
(52, 'Stand Firm', 'Strength', 'Cannot be pushed unless Knocked Down.'),
(53, 'Strong Arm', 'Strength', '+1 to Throw Team-mate Passing Ability tests.'),
(54, 'Thick Skull', 'Strength', 'On KO, roll D6: 4+ results in Stun instead of KO.'),

-- MUTATION
(55, 'Big Hand', 'Mutation', 'Ignores tackle zones when picking up the ball.'),
(56, 'Claws', 'Mutation', 'Armour breaks on 8+ regardless of target''s Armour Value.'),
(57, 'Disturbing Presence', 'Mutation', '-1 to opponents'' Passing, Catch, or Intercept tests within 3 squares.'),
(58, 'Extra Arms', 'Mutation', '+1 to Pick-up, Intercept, and Catch rolls.'),
(59, 'Foul Appearance', 'Mutation', 'Opponent rolls D6 before Block; on 1, the Block automatically fails.'),
(60, 'Horns', 'Mutation', '+1 Strength when Blitzing.'),
(61, 'Iron Hard Skin', 'Mutation', 'Unaffected by Claws skill.'),
(62, 'Monstrous Mouth', 'Mutation', 'Rerolls failed Catch rolls and immune to Strip Ball effects.'),
(63, 'Prehensile Tail', 'Mutation', '-1 to Dodge rolls for opponents dodging away from this player.'),
(64, 'Tentacles', 'Mutation', 'Make it difficult for oppents to escape; opponents must roll 2D6 + Strength to break free.'),
(65, 'Two Heads', 'Mutation', '+1 to Dodge rolls.'),
(66, 'Very Long Legs', 'Mutation', 'This player may reduce any negative modifier applied to the Agility test when they attempt to Jump over a Prone Player.'),

-- EXTRAORDINARY
(67, 'Always Hungry', 'Extraordinary', 'Roll D6 when attempting Throw Team-mate; on 1, player attempst to eat Team-mate.'),
(68, 'Animal Savagery', 'Extraordinary', 'On activation, roll D6; on 1-3, must Block adjacent team-mate or lose activation.'),
(69, 'Animosity', 'Extraordinary', 'Refuse handover or Pass to teammate if rolls 1 on D6.'),
(70, 'Ball & Chain', 'Extraordinary', 'When this player is activated, the only action they may perform is a “Ball and Chain Move” special action.'),
(71, 'Bloodlust', 'Extraordinary', 'Roll a D6 each activation, and if they fail, they must bite a nearby Thrall by the end of their turn or cause a Turnover, lose their Tackle Zone, and drop the ball.'),
(72, 'Bombardier', 'Extraordinary', 'May throw bombs instead of moving.'),
(73, 'Bone Head', 'Extraordinary', 'Roll D6 on activation; on 1, lose Tackle Zones and end activation.'),
(74, 'Breathe Fire', 'Extraordinary', 'May perform a fiery breath attack instead of a Block.'),
(75, 'Chainsaw', 'Extraordinary', 'Instead of blocking, perform a "Chainsaw Attack".'),
(76, 'Decay', 'Extraordinary', '+1 applied to all rolls against this player on the Casualty table.'),
(77, 'Drunkard', 'Extraordinary', '-1 penality to the dice roll when attempting to Rush.'),
(78, 'Fan Favorite', 'Extraordinary', '+1 FAME modifier for any Kick-Off table results, but not for the Winnings roll.'),
(79, 'Hit and Run', 'Extraordinary', 'After a Block action, player can move one free square if still Standing and not Marked.'),
(80, 'Hypnotic Gaze', 'Extraordinary', 'Replaces Block with Agility test to remove opponent tackle zones.'),
(81, 'Kick Team-mate', 'Extraordinary', 'May kick a team-mate.'),
(82, 'Loner', 'Extraordinary', 'Must roll 4+ to use team rerolls.'),
(83, 'My Ball', 'Extraordinary', 'Can not Pass, Hand-off or willingly let go of ball.'),
(84, 'No Hands', 'Extraordinary', 'Unable to pick up, intercept, carry or catch the ball.'),
(85, 'Pick-Me-Up', 'Extraordinary', 'On a 5+, any Prone player within 3 squares may stand up.'),
(86, 'Plague Ridden', 'Extraordinary', 'Potentially gain a journeyman from first casualty.'),
(87, 'Pogo Stick', 'Extraordinary', 'May choose to Leap over any single adjacent square, without penalty.'),
(88, 'Projectile Vomit', 'Extraordinary', 'May perform a vomit attack instead of blocking'),
(89, 'Really Stupid', 'Extraordinary', 'May lose activation randomly.'),
(90, 'Regeneration', 'Extraordinary', 'On a 4+, the Casualty roll is discarded without effect and player placed in Reserves box.'),
(91, 'Right Stuff', 'Extraordinary', 'Can be thrown by a team-mate with the Throw Team-mate skill.'),
(92, 'Secret Weapon', 'Extraordinary', 'At end of drive, player will be Sent-off for committing a Foul.'),
(93, 'Stab', 'Extraordinary', 'Make an unmodified Armour roll against the target, instead of blocking.'),
(94, 'Stakes', 'Extraordinary', '+1 to Armour roll when making Stab attack against Khemri, Necromantic, Undead or Vampire'),
(95, 'Stunty', 'Extraordinary', 'Ignore -1 modifiers when dodging when Marked in the square they have moved into.'),
(96, 'Swarming', 'Extraordinary', 'During start of drive, add D3 players from reserve box onto pitch.'),
(97, 'Swoop', 'Extraordinary', 'May "swoop" when thrown.'),
(98, 'Take Root', 'Extraordinary', 'Every activation, roll D6. If rolled 1, lose movement until knocked over.'),
(99, 'Throw Team-Mate', 'Extraordinary', 'Perform a Throw Team-mate action.'),
(100, 'Timmm-ber!', 'Extraordinary', 'Adjacement friendly players add +1 to standup roll. 1 is always a failure.'),
(101, 'Titchy', 'Extraordinary', 'This player may apply a +1 modifier to any Agility tests they make in order to Dodge.'),
(102, 'Trickster', 'Extraordinary', 'When block declared on this player, move to any adjacement square of blocking player.'),
(103, 'Unchannelled Fury', 'Extraordinary', 'Roll 2+ if blocking or blitzing, otherwise 4+, to not end activation.');

INSERT INTO skill_category (id, name, description) VALUES
(1, 'General', 'General skills and intelligence-based actions.'),
(2, 'Agility', 'Skills that improve dodging, catching, and movement agility.'),
(3, 'Strength', 'Skills that enhance physical strength and blocking capabilities.'),
(4, 'Passing', 'Skills that improve passing and ball handling.'),
(5, 'Mutations', 'Special skills related to mutations and unique traits.');

INSERT INTO skill_random_selection
(first_d6, second_d6, agility_skill, general_skill, mutations_skill, passing_skill, strength_skill) VALUES
(1, 1, 'Catch', 'Block', 'Big Hand', 'Accurate', 'Arm Bar'),
(1, 2, 'Diving Catch', 'Dauntless', 'Claws', 'Cannoneer', 'Brawler'),
(1, 3, 'Diving Tackle', 'Dirty Player (+1)', 'Disturbing Presence*', 'Cloud Burster', 'Break Tackle'),
(1, 4, 'Dodge', 'Fend', 'Extra Arms', 'Dump-off', 'Grab'),
(1, 5, 'Defensive', 'Frenzy*', 'Foul Appearance*', 'Fumblerooskie', 'Guard'),
(1, 6, 'Jump Up', 'Kick', 'Horns', 'Hail Mary Pass', 'Juggernaut'),
(2, 1, 'Leap', 'Pro', 'Iron Hard Skin', 'Leader', 'Mighty Blow (+1)'),
(2, 2, 'Safe Pair of Hands', 'Shadowing', 'Monstrous Mouth', 'Nerves of Steel', 'Multiple Block'),
(2, 3, 'Sidestep', 'Strip Ball', 'Prehensile Tail', 'On the Ball', 'Pile Driver'),
(2, 4, 'Sneaky Git', 'Sure Hands', 'Tentacles', 'Pass', 'Stand Firm'),
(2, 5, 'Sprint', 'Tackle', 'Two Heads', 'Running Pass', 'Strong Arm'),
(2, 6, 'Sure Feet', 'Wrestle', 'Very Long Legs', 'Safe Pass', 'Thick Skull');