INSERT INTO skill (id, name, category, description) VALUES
-- GENERAL
(1, 'Block', 'General', 'A player with the Block skill is proficient at knocking opponents down. The Block skill, if used, affects the results rolled with the Block dice, as explained in the Blocking rules.'),
(2, 'Dauntless', 'General', "When blocking a stronger opponent, roll a D6 and add it to the player's Strength. If the total exceeds the opponent's Strength, the player temporarily matches the opponent's Strength for that block. If not, the player uses their normal Strength. This roll happens before assists but after other modifiers."),
(3, 'Dirty Player', 'General', 'Adds +1 to Armour or Injury rolls when Fouling.'),
(4, 'Fend', 'General', 'Opponents cannot follow up after pushing this player back.'),
(5, 'Frenzy', 'General', 'Must follow up and attempt a second Block if the initial Block pushes the opponent back.'),
(6, 'Kick', 'General', 'Improves control over kick placement during Kick-Off.'),
(7, 'Kick-Off Return', 'General', 'Allows additional movement during Kick-Off Return.'),
(8, 'Pass Block', 'General', 'This player blocks the passer instead of the ball carrier.'),
(9, 'Pro', 'General', 'Once per turn, may reroll any single dice roll of 3 or higher.'),
(10, 'Shadowing', 'General', 'Follows adjacent moving opponents if winning opposed 2D6 + Movement roll.'),
(11, 'Strip Ball', 'General', 'When this player blocks an opponent carrying the ball, the ball scatters instead of being automatically caught.'),
(12, 'Sure Hands', 'General', 'Rerolls failed Pick-up rolls and immune to Strip Ball effects.'),
(13, 'Tackle', 'General', 'Prevents opponent from using Dodge skill when blocked or dodging into tackle zone.'),
(14, 'Wrestle', 'General', 'Can block with tackle zones and prevents Both Down results on pushes.'),

-- AGILITY
(15, 'Catch', 'Agility', 'A player who has the Catch skill is allowed to re-roll the D6 if he fails a catch roll. It also allows the player to re-roll the D6 if he drops a hand-off or fails to make an interception.'),
(16, 'Defensive', 'Agility', 'During your opponent’s team turn (but not during your own team), any opposition player being marked by this player cannot use the guard skill.'),
(17, 'Diving Catch', 'Agility', 'Can catch the ball from adjacent squares and gains +1 to Catch rolls for accurate passes.'),
(18, 'Diving Tackle', 'Agility', 'May go prone to apply -2 to adjacent opponent''s Dodge roll when they attempt to dodge away.'),
(19, 'Dodge', 'Agility', 'Allows rerolling failed Dodge rolls.'),
(20, 'Jump Up', 'Agility', 'Can stand up for free and block immediately without using movement.'),
(21, 'Leap', 'Agility', 'Leaps into adjacent squares ignoring tackle zones, applying -1 per opposing tackle zone entered.'),
(22, 'Safe Pair of Hands', 'Agility', 'If player Knocked Down, ball does not bounce.'),
(23, 'Sidestep', 'Agility', 'Chooses destination square when pushed.'),
(24, 'Sneaky Git', 'Agility', 'Not sent off for rolling doubles against Armour Roll.'),
(25, 'Sprint', 'Agility', 'Can Rush three times per turn.'),
(26, 'Sure Feet', 'Agility', 'Once per team turn, reroll a failed Rush.'),

-- PASSING
(27, 'Accurate', 'Passing', '+1 to Passing Ability tests when passing.'),
(28, 'Cannoneer', 'Passing', '+1 to Passing Ability tests for Long and Long Bomb passes.'),
(29, 'Cloud Burster', 'Passing', 'During Long Pass action or Long Bomb Pass action, make the opposing coach re-roll a successful attempt to interfere with the pass.'),
(30, 'Dump-Off', 'Passing', 'Allows a quick pass to a nearby teammate after a Block action.'),
(31, 'Fumblerooskie', 'Passing', 'Place/drop ball in vacated square without causing a turnover.'),
(32, 'Give and Go', 'Passing', 'After passing, allows moving again for a short distance.'),
(33, 'Hail Mary Pass', 'Passing', 'Declares a pass that automatically misses, but may target any square on the pitch.'),
(34, 'Leader', 'Passing', 'Grants one additional team reroll per half.'),
(35, 'Nerves of Steel', 'Passing', 'Ignores opponent tackle zones when Passing, Catching, or Intercepting.'),
(36, 'On The Ball', 'Passing', 'May move 3 squares when opponent declares a Pass or during Kick-Off.'),
(37, 'Pass', 'Passing', 'Once per turn rerolls a failed Passing Ability test.'),
(38, 'Portal Passer', 'Passing', 'During its activation, when this player teleports using a Portal, it may declare a Pass action after determining which Portal it is teleporting to.'),
(39, 'Running Pass', 'Passing', 'May continue moving after a successful Quick Pass.'),
(40, 'Safe Pass', 'Passing', 'Fumbled Pass does not cause turnover; ball remains in possession.'),
(41, 'Wall Thrower', 'Passing', 'When this player throws the ball at the wall, they may apply an additional +1 modifier when testing for the accuracy of the pass.'),

-- STRENGTH
(42, 'Arm Bar', 'Strength', '+1 to Armour rolls when opponent fails Dodge or Jump from adjacent square.'),
(43, 'Brawler', 'Strength', 'May reroll one Both Down result when blocking during own activation.'),
(44, 'Break Tackle', 'Strength', 'Once per activation, may use Strength instead of Agility for Dodge.'),
(45, 'Grab', 'Strength', 'May push opponents into any adjacent square, negating Side Step.'),
(46, 'Guard', 'Strength', 'Can assist Blocks regardless of being in opponent''s tackle zone.'),
(47, 'Juggernaut', 'Strength', 'During Blitz, treats Both Down results as Push; negates Stand Firm and Wrestle.'),
(48, 'Mighty Blow', 'Strength', '+1 to Armour or Injury roll after Block.'),
(49, 'Multiple Block', 'Strength', 'Blocks two adjacent opponents simultaneously with separate dice pools.'),
(50, 'Piling On', 'Strength', 'May follow up a Knock Down and immediately commit a Foul.'),
(51, 'Pile Driver', 'Strength', 'May follow up a Knock Down and immediately perform a second Block.'),
(52, 'Stand Firm', 'Strength', 'Cannot be pushed unless Knocked Down.'),
(53, 'Strong Arm', 'Strength', '+1 to Throw Team-mate Passing Ability tests.'),
(54, 'Thick Skull', 'Strength', 'On KO, roll D6: 4+ results in Stun instead of KO.'),

-- MUTATION
(55, 'Big Hand', 'Mutation', 'Ignores tackle zones when picking up the ball.'),
(56, 'Claws', 'Mutation', 'Armour breaks on 8+ regardless of target''s Armour Value.'),
(57, 'Disturbing Presence', 'Mutation', '-1 to opponents'' Passing, Catch, or Intercept tests within 3 squares.'),
(58, 'Extra Arms', 'Mutation', '+1 to Pick-up, Intercept, and Catch rolls.'),
(59, 'Foul Appearance', 'Mutation', 'Opponent rolls D6 before Block; on 1, the Block automatically fails.'),
(60, 'Horns', 'Mutation', '+1 Strength when Blitzing.'),
(61, 'Iron Hard Skin', 'Mutation', 'Unaffected by Claws skill.'),
(62, 'Monstrous Mouth', 'Mutation', 'Rerolls failed Catch rolls and immune to Strip Ball effects.'),
(63, 'Prehensile Tail', 'Mutation', '-1 to Dodge rolls for opponents dodging away from this player.'),
(64, 'Tentacles', 'Mutation', 'This player can use this Skill when an opposition player they are Marking voluntarily moves out of a square within this player’s Tackle Zone. Roll a D6, adding the ST of this player to the roll and then subtracting the ST of the opposition player. If the result is 6 or higher, or if the roll is a natural 6, the opposition player is held firmly in place and their movement comes to an end. If, however, the result is 5 or lower, or if the roll is a natural 1, this Skill has no further effect. A player may use this Skill any number or times per turn, during either team’s turn. If an opposition player is being Marked by more than one player with this Skill, only one player may use it.'),
(65, 'Two Heads', 'Mutation', '+1 to Dodge rolls.'),
(66, 'Very Long Legs', 'Mutation', '+2 to Intercept tests and ignores Cloud Burster.'),

-- EXTRAORDINARY
(67, 'Always Hungry', 'Extraordinary', 'Roll D6 when attempting Throw Team-mate; on 1, team-mate may be eaten.'),
(68, 'Animal Savagery', 'Extraordinary', 'On activation, roll D6; on 1-3, must Block adjacent team-mate or lose activation.'),
(69, 'Animosity', 'Extraordinary', 'This player is jealous of and dislikes certain other players of their team, as shown in brackets after the name of the Skill on this player’s profile.'),
(70, 'Ball & Chain', 'Extraordinary', 'When this player is activated, the only action they may perform is a “Ball and Chain Move” special action.'),
(71, 'Bloodlust', 'Extraordinary', 'Must attempt to Block each turn, losing activation if unable.'),
(72, 'Bombardier', 'Extraordinary', 'May throw bombs instead of moving.'),
(73, 'Bone Head', 'Extraordinary', 'Roll D6 on activation; on 1, lose Tackle Zones and end activation.'),
(74, 'Breathe Fire', 'Extraordinary', 'May perform a fiery breath attack instead of a Block.'),
(75, 'Chainsaw', 'Extraordinary', 'Adds +3 to Armour rolls when Blocking or Fouling; knocked down if turnover occurs.'),
(76, 'Decay', 'Extraordinary', 'Causes injury on opponent knockdowns.'),
(77, 'Drunkard', 'Extraordinary', 'May reroll failed Block dice but suffers penalties elsewhere.'),
(78, 'Fan Favorite', 'Extraordinary', 'Can use re-rolls on any dice rolls during the game.'),
(79, 'Hit and Run', 'Extraordinary', 'After a player with this Trait performs a Block action, they may immediately move one free square ignoring Tackle Zones so long as they are still Standing. They must ensure that after this free move, they are not Marked by or Marking any opposition players.'),
(80, 'Hypnotic Gaze', 'Extraordinary', 'Replaces Block with Agility test to remove opponent tackle zones.'),
(81, 'Kick Team-mate', 'Extraordinary', 'May kick a team-mate to move them instead of the ball.'),
(82, 'Loner', 'Extraordinary', 'Must roll 4+ to use team rerolls.'),
(83, 'My Ball', 'Extraordinary', 'Automatically catches the ball from any teammate within 3 squares.'),
(84, 'No Hands', 'Extraordinary', 'Cannot pick up or catch the ball.'),
(85, 'Pick-Me-Up', 'Extraordinary', 'Can pick up and throw teammates.'),
(86, 'Plague Ridden', 'Extraordinary', 'Once per game, if an opposition player with Strength characteristic of 4 or less that does not have the Decay, Regeneration or Stunty traits suffers a Casualty result of 15-16, DEAD as the result of a Block action performed or a Foul action committed by a player with this Trait that belongs to your team, and if that player cannot be saved by an apothecary, you may choose to use this Trait. If you do, that player does not die; they have instead been infected with a virulent plague! If your team has the ‘Favoured of Nurgle’ special rule, a new ‘Rotter Lineman’ player, drawn from the Nurgle roster, can be placed immediately in the Reserves box of your team’s dugout (this may cause a team to have more than 16 players for the remainder of this game). During step 4 of the post-game sequence, this player may be permanently hired, Exactly as you would a Journeyman player that had played for your team.'),
(87, 'Pogo Stick', 'Extraordinary', 'May leap over opponents without penalties.'),
(88, 'Projectile Vomit', 'Extraordinary', 'May perform a ranged vomit attack causing injury.'),
(89, 'Really Stupid', 'Extraordinary', 'May lose activation randomly.'),
(90, 'Regeneration', 'Extraordinary', 'Rerolls KO and injury results.'),
(91, 'Right Stuff', 'Extraordinary', 'Ignores injury on turnover results.'),
(92, 'Secret Weapon', 'Extraordinary', 'Appears randomly in the team; unknown until activated.'),
(93, 'Stab', 'Extraordinary', 'Ignores armour on injury rolls.'),
(94, 'Stakes', 'Extraordinary', 'Causes extra damage when causing injuries.'),
(95, 'Stunty', 'Extraordinary', 'Small size; harder to hit but also harder to block.'),
(96, 'Swarming', 'Extraordinary', 'Multiple players may gang up to Block a single opponent.'),
(97, 'Swoop', 'Extraordinary', 'May swoop into any square without movement penalties.'),
(98, 'Take Root', 'Extraordinary', 'Cannot be pushed when standing still.'),
(99, 'Throw Team-Mate', 'Extraordinary', 'May throw teammates to other squares.'),
(100, 'Timmm-ber!', 'Extraordinary', 'May chop down opponents blocking movement.'),
(101, 'Titchy', 'Extraordinary', 'Small stature; harder to hit with Blocks.'),
(102, 'Trickster', 'Extraordinary', 'Can reroll opponent''s successful dice rolls once per turn.'),
(103, 'Unchannelled Fury', 'Extraordinary', 'Must always Block an opponent when able.');

INSERT INTO skill_category (id, name, description) VALUES
(1, 'General', 'General skills and intelligence-based actions.'),
(2, 'Agility', 'Skills that improve dodging, catching, and movement agility.'),
(3, 'Strength', 'Skills that enhance physical strength and blocking capabilities.'),
(4, 'Passing', 'Skills that improve passing and ball handling.'),
(5, 'Mutations', 'Special skills related to mutations and unique traits.');

INSERT INTO skill_random_selection
(first_d6, second_d6, agility_skill, general_skill, mutations_skill, passing_skill, strength_skill) VALUES
(1, 1, 'Catch', 'Block', 'Big Hand', 'Accurate', 'Arm Bar'),
(1, 2, 'Diving Catch', 'Dauntless', 'Claws', 'Cannoneer', 'Brawler'),
(1, 3, 'Diving Tackle', 'Dirty Player (+1)', 'Disturbing Presence*', 'Cloud Burster', 'Break Tackle'),
(1, 4, 'Dodge', 'Fend', 'Extra Arms', 'Dump-off', 'Grab'),
(1, 5, 'Defensive', 'Frenzy*', 'Foul Appearance*', 'Fumblerooskie', 'Guard'),
(1, 6, 'Jump Up', 'Kick', 'Horns', 'Hail Mary Pass', 'Juggernaut'),
(2, 1, 'Leap', 'Pro', 'Iron Hard Skin', 'Leader', 'Mighty Blow (+1)'),
(2, 2, 'Safe Pair of Hands', 'Shadowing', 'Monstrous Mouth', 'Nerves of Steel', 'Multiple Block'),
(2, 3, 'Sidestep', 'Strip Ball', 'Prehensile Tail', 'On the Ball', 'Pile Driver'),
(2, 4, 'Sneaky Git', 'Sure Hands', 'Tentacles', 'Pass', 'Stand Firm'),
(2, 5, 'Sprint', 'Tackle', 'Two Heads', 'Running Pass', 'Strong Arm'),
(2, 6, 'Sure Feet', 'Wrestle', 'Very Long Legs', 'Safe Pass', 'Thick Skull');